USE [KN_online]
GO

CREATE TABLE [USERDATA_SKILLSHORTCUT] (
	[strCharID] varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[nCount] smallint NOT NULL,
	[strSkillData] varchar(260) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	CONSTRAINT [PK_USERDATA_SKILLSHORTCUT] PRIMARY KEY CLUSTERED ([strCharID])
)
GO
ALTER TABLE [USERDATA_SKILLSHORTCUT] ADD CONSTRAINT [DF_USERDATA_SKILLSHORTCUT_strCharID] DEFAULT '' FOR [strCharID]
GO
ALTER TABLE [USERDATA_SKILLSHORTCUT] ADD CONSTRAINT [DF_USERDATA_SKILLSHORTCUT_nCount] DEFAULT 0 FOR [nCount]
GO
ALTER TABLE [USERDATA_SKILLSHORTCUT] ADD CONSTRAINT [DF_USERDATA_SKILLSHORTCUT_strSkillData] DEFAULT 0x00 FOR [strSkillData]
GO
